### ISSUE TITLE
Add a subscriber and keep his status

### ISSUE THREAD

**Issue by fernandopg** [gellu/sendy-api#4]
Hi @gellu, first of all great job with this RestFull api!

I am trying to add subscribers to a new list through the api but when I added, them all appear as  'subscribed'.

Is there any option to add a subscriber in a new list and keep his status (from other existing lists).

Thanks!

**Comment by gellu** [comment]
Thx :)

Unfortunately this can't be done. User can be subscribed to some list and unsubscribed from other. There is no way to get consistent user subscription status across all lists.

You can always use method ```/subscribers/get/user``` to get all subscription statuses for user.

I hope it helps. Let me know if that is what you need.

**Comment by fernandopg** [comment]
Thanks Gellu!

That's strange, I can see in the Sendy list options that there is an option that you can choose if you want to unsubscribe a user from all the lists in the same brand if the user is unsubscribed in that list.

![captura de pantalla 2015-08-10 a las 20 34 31](https://cloud.githubusercontent.com/assets/823395/9179838/4eff5762-3f9f-11e5-89b1-6a8c8d5de163.png)

By default this option is in 'All lists', so when you unsubscribe a user through the API in a list, he is unsubscribed automatically from the other lists.

I make the tests with the Sendy API: **POST http://your_sendy_installation/unsubscribe** and it works properly, with your API **POST http://your_sendy_installation/subscribers/user/unsubscribe?app_key=your_app_key** this is not working...

So I am going to fork and make that change to work like at the official API and if you want I can make a PULL REQUEST to add it to your awesome API! ;-)

Another behavior that also I want to add is that if you add a user in a list with 'All Lists' unsubscribe option checked, if that user was unsubscribed previously in any other list I am going to keep his status! (That is not currently happening in the official API... I don't know why...) If you want also that feature in your API please tell me and I will make other PULL REQUEST!

Thanks a lot again for your API, is saving my time a lot!

**Comment by gellu** [comment]
Unsubscribe from all list can be done - if you can do it and make a pull request, that would be awesome :)

About adding user with unsubscribed status. I don't get the concept. Why would you want to add user to another list with unsubscribed status? It's like you would never add him, because he would not get any emails.

**Comment by fernandopg** [comment]
Talking about this:
"About adding user with unsubscribed status. I don't get the concept. Why would you want to add user to another list with unsubscribed status? It's like you would never add him, because he would not get any emails."

Yes, that's true. I think that the best option is not to add the user. I know that you can always use method /subscribers/get/user first to get all subscription statuses for user but maybe in the meantime that you check and then add him the user has unsubscribed from other list...

For this reason I think that is important to ad that feature! What do you think?

**Comment by gellu** [comment]
How you plan to determine user status?

If the user is subscribed to 3 lists and unsubscribed from one list. What will be he his status in new subscription that will be added?

**Comment by fernandopg** [comment]
Hi @gellu !

My idea is to do that only when the list was created as 'Unsubscribe from all list'; so if the user is in 'unsubscribed' status in any list also with 'Unsubscribe from all list' option checked I don't add the user to the list.

**Comment by gellu** [comment]
I don't see the field in Sendy DB which will tell that user is 'Unsubscribe from all list'.
I believe that Sendy is updating all rows in subscribers for specified user with unsubscribed = 1 when 'Unsubscribe from all list' is checked.
